name: CI -> Compose, compile SCSS and deploy


on:
  push:
    branches: [master]
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  compile:
    name: ğŸ–¼ï¸ Compile
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: ğŸ”¨ Compose App
        uses: php-actions/composer@v6

      - name: Make destination directory for compiled CSS
        run: mkdir -vp css

      - name: ğŸ—œï¸ Compile SCSS
        uses: gha-utilities/sass-build@v0.4.8
        with:
          source: _scss/common.scss
          destination: css/common.css

      # Minify Files
      - name: ğŸ”¨ Compress Web files
        uses: zugazagoitia/minify-js@v0.4

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.event.head_commit.id }}

  deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest

    needs:
      - compile

    steps:
      # Deploy

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.event.head_commit.id }}

      - name: ğŸ“‚ RSync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -vzr --delete --exclude=".git/" --exclude="_scss/" --exclude="config/" --exclude=".github/" --exclude="DOCKER_ENV" --exclude="output.log" --exclude="docker_tag"
          remote_path: ${{ secrets.SSH_REMOTE_DIR }}
          remote_host: ${{ secrets.SSH_SERVER }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

